id = "hujson"
name = "HuJSON"
version = "1.0.1"
schema_version = 1
description = "HuJSON (JWCC) support: JSON with comments and trailing commas"
authors = ["Gareth Evans <hi@gvns.ca>"]
repository = "https://github.com/ggfevans/zed-hujson"
languages = ["languages/hujson"]

[grammars.hujson]
repository = "https://github.com/ggfevans/tree-sitter-hujson"
rev = "506ab946025772028c0050d8c6b555ef5670f4b5"
